[macros.install__arch]
  prefix = ["sudo", "pacman", "-S"]

[macros.install__ubuntu]
  prefix = ["sudo", "apt-get", "install", "-y"]

[macros.clone]
  prefix = ["git", "clone"]

[tasks.desktop]
  deps = ["common", "asdf"]
  links = [
    [".config/i3", ".config/i3-desktop"],
    [".asdfrc"]
  ]
  
[tasks.common]
  deps = ["neovim", "zsh"]
  links = [
    [".config/nvim"],
    [".zshrc"],
    [".gitconfig"],
    [".gitignore"]
  ]

[tasks.neovim]
  rejects = [["which", "nvim"]]
  cmds = [["@install", "neovim"]]

[tasks.asdf]
  rejects = [["which", "asdf"]]
  cmds = [["@clone", "git://github.com/asdf-vm/asdf.git", "./.asdf"]]

[tasks.zsh]
  rejects = [["which", "zsh"]]
  cmds = [
    ["@install", "zsh"], 
    ["chsh", "-s", "/usr/bin/zsh"],
    ["@clone", "git://github.com/robbyrussell/oh-my-zsh.git", "./.oh-my-zsh"]
  ]
