[macros.install__arch]
  prefix = ["sudo", "pacman", "-S"]

[macros.install__ubuntu]
  prefix = ["sudo", "apt-get", "install", "-y"]

[macros.clone]
  prefix = ["git", "clone"]

[tasks.desktop]
  deps = ["common", "asdf"]
  links = [
    [".config/i3", ".config/i3-desktop"],
    [".Xresources"],
    [".asdfrc"]
  ]
  
[tasks.common]
  deps = ["neovim", "zsh"]
  links = [
    [".config/nvim"],
    [".zshrc"],
    [".ctags"],
    [".gitconfig"],
    [".gitignore_global"]
  ]

[tasks.neovim]
  rejects = [["which", "nvim"]]
  cmds = [["@install", "neovim"]]

[tasks.asdf]
  rejects = [["which", "asdf"]]
  cmds = [["@clone", "git://github.com/asdf-vm/asdf.git", "./.asdf"]]

[tasks.zsh]
  cmds = [
    ["@clone", "git://github.com/robbyrussell/oh-my-zsh.git", "./.oh-my-zsh"]
  ]

[tasks.bootstrap__arch]
  cmds = [
    ["@install", "python3", "python-pip", "ruby", "ctags", "xorg-xrdb"],
    ["sudo", "pip", "install", "--upgrade", "pip"],
    ["sudo", "pip", "install", "neovim"],
    ["gem", "install", "neovim"],
    ["@clone", "https://github.com/Lokaltog/powerline-fonts", ".fonts"],
    ["fc-cache", "-vf", ".fonts"]
  ]
