[macros.install__arch]
  prefix = ["sudo", "pacman", "-S"]

[macros.install__ubuntu]
  prefix = ["sudo", "apt-get", "install", "-y"]

[tasks.desktop]
  deps = ["common"]
  links = [
    [".config/i3", ".config/i3-desktop"]
  ]
  
[tasks.common]
  deps = ["neovim", "zsh"]
  links = [
    [".config/nvim"],
    [".zshrc"],
    [".gitconfig"],
    [".gitignore"]
  ]

[tasks.neovim]
  rejects = [["which", "nvim"]]
  cmds = [["@install", "neovim"]]

[tasks.zsh]
  rejects = [["which", "zsh"]]
  cmds = [
    ["@install", "zsh"], 
    ["chsh", "-s", "/usr/bin/zsh"],
    ["git", "clone", "git://github.com/robbyrussell/oh-my-zsh.git", "~/.oh-my-zsh"]
  ]
